-- SOFTWARE MANAGEMENT SYSTEM
-- CREATE TABLES

CREATE TABLE DEVELOPER (
    Developer_ID NUMBER PRIMARY KEY,
    Developer_Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    Contact VARCHAR2(15)
);

CREATE TABLE CATEGORY (
    Category_ID NUMBER PRIMARY KEY,
    Category_Name VARCHAR2(50) NOT NULL,
    Description VARCHAR2(200)
);

CREATE TABLE LICENSE (
    License_ID NUMBER PRIMARY KEY,
    License_Type VARCHAR2(50) NOT NULL,
    Start_Date DATE,
    Expiry_Date DATE,
    Status VARCHAR2(20)
);

CREATE TABLE "USER" (
    User_ID NUMBER PRIMARY KEY,
    User_Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    Department VARCHAR2(100),
    Contact VARCHAR2(15)
);

CREATE TABLE SOFTWARE (
    Software_ID NUMBER PRIMARY KEY,
    Software_Name VARCHAR2(100) NOT NULL,
    Version VARCHAR2(20) NOT NULL,
    Developer_ID NUMBER,
    Category_ID NUMBER,
    License_ID NUMBER,

    CONSTRAINT FK_SOFTWARE_DEVELOPER
        FOREIGN KEY (Developer_ID)
        REFERENCES DEVELOPER(Developer_ID),

    CONSTRAINT FK_SOFTWARE_CATEGORY
        FOREIGN KEY (Category_ID)
        REFERENCES CATEGORY(Category_ID),

    CONSTRAINT FK_SOFTWARE_LICENSE
        FOREIGN KEY (License_ID)
        REFERENCES LICENSE(License_ID)
);

CREATE TABLE INSTALLATION (
    Installation_ID NUMBER PRIMARY KEY,
    Software_ID NUMBER,
    User_ID NUMBER,
    Install_Date DATE,
    System_Name VARCHAR2(100),
    Status VARCHAR2(20),

    CONSTRAINT FK_INSTALL_SOFTWARE
        FOREIGN KEY (Software_ID)
        REFERENCES SOFTWARE(Software_ID),

    CONSTRAINT FK_INSTALL_USER
        FOREIGN KEY (User_ID)
        REFERENCES "USER"(User_ID)
);
